# **Biblioteca NumPy**

## Introdução 
*Olá devers, beleza?*


Hoje faremos uma introdução a biblioteca NumPy, explorando recursos básicos e conceitos da biblioteca utilizada na geração dos dados da **primeira imagem de um buraco negro!**


Além disso, vamos abordar a aplicabilidade dessa biblioteca por meio de exemplos práticos e usos no cotidiano.
<br><br>
<div align="center">
    <img src="https://i.redd.it/791y1x3j2ou41.png" alt="titulo" width="300px" />
</div>


## **O que é o NumPy?**
É uma biblioteca (conjunto de módulos,funções e classes pré-definidos) em Python que permite a manipulação de dados homogêneos dentro de um elemento conhecido como *Array*. 

*Pontos positivos:* 
- Apesar de realizar tarefas que já existem dentro do Python (que seriam feitas em iterables built-in), o numpy fornece maior velocidade e eficiência de processos numéricos, diminuindo o uso de loops no código em comparação aos códigos tradicionais, além de realizar operações vetorizadas.

- Além disso possui integração com outras bibliotecas externas como o **Pandas**, **Seaborn** e **MatPlotLib**, facilitando a manipulação de dados.

*Pontos negativos:*
- Lida apenas com dados homogêneos, dificultando operações entre dados string, booleans e numéricos dentro de um vetor.

- Não possui uma integração tão básica com funções built-in, sendo as vezes restringida as suas próprias funções internas.


###### * Também traz um decréscimo no uso de memória RAM e processamento devido a ser uma biblioteca programada em C, uma linguagem de baixo nível.


In [3]:
# Começaremos importando a biblioteca, como na imagem acima
import numpy as np

### Array e dimensionamento:

Um dos benefícios dessa biblioteca consiste na facilidade com trabalhar e operar "listas" de dados (arrays), principalmente os numéricos. Para isso começaremos entendendo como funciona a função np.array()

In [4]:
array_lin_ex = np.array([1,6,7])
print(f' Exemplo de array com apenas uma linha:{array_lin_ex}')

print("-" * 60)

array_matrix_2x2 = np.array([[1,2],[6,7]])
print(f'''Exemplo de array bidimensional:
{array_matrix_2x2}''')

print("-" * 60)

array_matrix_3x4 = np.array([[6,0,100],[17,16,54],[20,49,48],[45,79,24]])
print(f'''Exemplo de array multidimensional:
{array_matrix_3x4}''')

 Exemplo de array com apenas uma linha:[1 6 7]
------------------------------------------------------------
Exemplo de array bidimensional:
[[1 2]
 [6 7]]
------------------------------------------------------------
Exemplo de array multidimensional:
[[  6   0 100]
 [ 17  16  54]
 [ 20  49  48]
 [ 45  79  24]]


### Atributos de array

In [5]:
arr = np.array([['a','e',0,True],['1',5,6,False]])

# Tamanho do array
tamanho_array = arr.shape

# Tipo do Array
tipo_array = arr.dtype

# Memória armazenada
ram_array = arr.data

# Número de dimensões do array 
ndimensoes_array = array_matrix_3x4.ndim

print(f'''{arr}
--------------------------------------------------      
|  Atributos:                                    |
| - Tamanho da matriz = {tamanho_array} ;                 |
| - Tipo de dado da matriz = {tipo_array} ;              |
| - Número de dimensões = {ndimensoes_array}                      |
--------------------------------------------------''')


[['a' 'e' '0' 'True']
 ['1' '5' '6' 'False']]
--------------------------------------------------      
|  Atributos:                                    |
| - Tamanho da matriz = (2, 4) ;                 |
| - Tipo de dado da matriz = <U11 ;              |
| - Número de dimensões = 2                      |
--------------------------------------------------


### Operações Básicas

As operações básicas nas arrays do NumPy são elemento a elemento, e essas operações só funcionam em arrays de mesmo tamanho. Aqui, falaremos um pouco mais sobre operações aritméticas básicas, tais como adição, subtração, multiplicação e divisão, em arrays. Mas, respeitando o passo-a-passo, verificaremoss 1) como criamos um array, 2) como acessar elementos de um array, e 3) como alterar elementos dentro de um array.

In [6]:
# Criando arrays

arr = np.array([1, 2, 3, 4, 5])

In [7]:
# Acessar elementos #

print(arr[0])     
print(arr[2:4])  

1
[3 4]


In [8]:
# Alterar elementos #

arr[0] = 10
print(arr)    

[10  2  3  4  5]


Agora, seguindo para as operações básicas:

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Soma #

c = a + b
print(c)

# Subtração #

d = a -  b
print(d)

# Multiplicação #

e = a * b
print(e)

# Divisão #

f = b / a
print(f)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[4.  2.5 2. ]


O NumPy oferece funções específicas para executar operações aritméticas, como np.add(), np.subtract(), np.multiply(), np.divide(), np.power(), entre outras. 

In [10]:
# np.add() - utilizada para adição elemento a elemento entre dois arrays ou um array e um escalar.

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.add(a, b)
print(c)

[5 7 9]


In [11]:
# np.subtract () - utilizada para realizar a subtração elemento a elemento entre dois arrays ou um array e um escalar.

d = np.subtract(b, a)
print(d)

[3 3 3]


In [12]:
# np.multiply() - usada para realizar multiplicação elemento a elemento entre dois arrays ou um array e um escalar.

e = np.multiply(a, b)
print(e)

[ 4 10 18]


In [13]:
# np.divide() - usada para realizar divisão elemento a elemento entre dois arrays ou um array e um escalar. 

f = np.divide(b, a)
print(f)

[4.  2.5 2. ]


In [14]:
# np.power() - usada para calcular a exponenciação elemento a elemento entre dois arrays ou um array e um escalar.

g = np.array([2, 3, 4])
h = np.array([2, 2, 2])

i = np.power(g, h)
print(i) 

[ 4  9 16]


Essas operações são especialmente úteis quando precisamos aplicar uma operação a vários arrays simultaneamente ou para salvarmos o resultado em um novo array.

Ademais, para filtrar um array no NumPy, temos duas opções: você pode usar a indexação booleana ou a função np.where().

In [15]:
# Indexação booleana 

arr = np.array([1, 2, 3, 4, 5])
filtro = arr > 3
resultado = arr[filtro]

print(resultado)

[4 5]


In [16]:
# Função np.where()

arr = np.array([1, 2, 3, 4, 5])
resultado = np.where(arr > 3)

print(resultado) 
# Operação retorna array com os índices dos elementos que atendem à condição. 
# Nesse caso, os índices 3 e 4 correspondem aos elementos 4 e 5.

(array([3, 4], dtype=int64),)


Além disso, o NumPy fornece o módulo np.random para gerar arrays com valores aleatórios. Algumas funções para criar arrays com números aleatórios são:

In [17]:
# np.random.randn(): Gera um array de números aleatórios com distribuição normal padrão (média 0 e desvio padrão 1) com uma forma especificada.

arr3 = np.random.randn(5)
print(arr3)

[ 0.23216216 -0.02321413 -0.94653799  0.88488116  1.18197746]


In [18]:
# np.random.randint(): Gera um array de números inteiros aleatórios dentro de um intervalo especificado.

arr5 = np.random.randint(10, size=5)
print(arr5)

[6 4 5 0 6]


Finalmente, alguns exemplos de operações mistas são:

In [19]:
import numpy as np

# Cria-se os arrays 

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Efetua as operações mistas

# soma 'a' com o dobro de 'b' 
resultado1 = a + 2 * b
print("Resultado 1:", resultado1)  

# multiplica os elementos de 'a' por 'b' e divide a soma desses elementos pelo somatório de 'a' e 'b'
resultado2 = np.sum(a * b) / np.sum(a + b)
print("Resultado 2:", resultado2)

Resultado 1: [ 9 12 15]
Resultado 2: 1.5238095238095237


### Funções universais

As funções universais no Numpy são funções matemáticas simples. É apenas um termo que demos às funções matemáticas na biblioteca Numpy, que cobrem uma ampla variedade de operações. Essas funções incluem funções trigonométricas padrão, funções para operações aritméticas, manipulação de números complexos, funções estatísticas, etc. Essas funções possuem como características principais:

Dentre as principais funções universais matemáticas estão:

* `sin`, `cos`, `tan`: calcular seno, cosseno e tangente de ângulos.

In [20]:
angulos_notaveis_deg = np.array([30,45,60])
angulos_notaveis_rad = np.deg2rad(angulos_notaveis_deg)

# Calculando o seno, cosseno e tangente de cada ângulo radianos usando as funções np.sin(), np.cos() enp.tan().
seno_notaveis = [np.round(elem,2) for elem in np.sin(angulos_notaveis_rad)]
cosseno_notaveis = [np.round(elem,2) for elem in np.cos(angulos_notaveis_rad)]
tangente_notaveis = [np.round(elem,2) for elem in np.tan(angulos_notaveis_rad)]

print('Seno, cosseno e tangente de 30 graus: ',seno_notaveis[0],', ',cosseno_notaveis[0],' e ',tangente_notaveis[0])
print('Seno, cosseno e tangente de 45 graus: ',seno_notaveis[1],', ',cosseno_notaveis[1],' e ',tangente_notaveis[1])
print('Seno, cosseno e tangente de 60 graus: ',seno_notaveis[2],', ',cosseno_notaveis[2],' e ',tangente_notaveis[2])


Seno, cosseno e tangente de 30 graus:  0.5 ,  0.87  e  0.58
Seno, cosseno e tangente de 45 graus:  0.71 ,  0.71  e  1.0
Seno, cosseno e tangente de 60 graus:  0.87 ,  0.5  e  1.73


* `hypot`: calcule a hipotenusa do triângulo retângulo dado.

In [21]:
x = np.array([3, 4, 3])
y = np.array([6, 8, 4])

hipotenusa = np.hypot(x, y)

print(hipotenusa)

[6.70820393 8.94427191 5.        ]


* `deg2rad`: converter grau em radianos.
* `rad2deg`: converter radianos em graus.

In [22]:
# Ângulo em graus
angulo_graus = 45

# Convertendo graus para radianos usando a função deg2rad
angulo_radianos = np.deg2rad(angulo_graus)

print("Ângulo em radianos:", angulo_radianos)

# Convertendo radianos para graus usando a função rad2deg
angulo_graus_novo = np.rad2deg(angulo_radianos)

print("Ângulo em graus:", angulo_graus_novo)

Ângulo em radianos: 0.7853981633974483
Ângulo em graus: 45.0


Dentre as principais funções universais estatísticas estão:

* `amin`, `amax`: retorna o mínimo ou máximo de um array ou ao longo de um eixo.


In [23]:
ex = np.array([1,3,5,7,10])

print('Array x = ',ex)
print('\nMínimo de x = ',np.amin(ex))
print('Máximo de x = ',np.amax(ex))


Array x =  [ 1  3  5  7 10]

Mínimo de x =  1
Máximo de x =  10


* `ptp`: retorna o intervalo de valores (máximo-mínimo) de um array ou ao longo de um eixo.

In [24]:
print('Intervalo de x = ',np.ptp(ex))

Intervalo de x =  9


* `sum`: retorna a soma de valores de um array ao longo de um eixo.

In [25]:
print('Soma de x = ',np.sum(ex))

Soma de x =  26


* `percentile(a, p, eixo)`: calcular o p-ésimo percentil da matriz ou ao longo do eixo especificado.

In [26]:
percentil_50 = np.percentile(ex, 50)

# Imprimindo o resultado
print("Percentil 50:", percentil_50)

Percentil 50: 5.0


* `median`: calcular a mediana dos dados ao longo do eixo especificado.
* `mean`: calcular a média dos dados ao longo do eixo especificado.
* `var`: calcular a variância de dados ao longo do eixo especificado.

In [27]:
print('Médiana de x = ',np.median(ex))
print('Média de x = ',np.mean(ex))
print('Variância de x = ',np.var(ex))


Médiana de x =  5.0
Média de x =  5.2
Variância de x =  9.76


* `log`: calcular o log dos dados ao longo do eixo especificado.

In [28]:
print('Log de x = ',[np.round(elem,2) for elem in np.log(ex)])

Log de x =  [0.0, 1.1, 1.61, 1.95, 2.3]


## Arrays x Listas

Vamos entender um pouco melhor a diferença de desempenho entre arrays e listas. Considere um array de vinte milhões de números inteiros e uma lista equivalente:

In [29]:
array = np.arange(20000000) #20 milhões
lista = list(range(20000000))

Agora vamos multiplicar, elemento a elemento, todos os números por 2 e salvar o resultado correspondente. Utilizaremos a função `time` do pacote `time` para fazer a medição do tempo utilizado pelos dois métodos.

In [30]:
import time 

# arrays
inicio_array = time.time()
array2 = array * 2
fim_array   = time.time()


# listas
inicio_lista = time.time()
lista2 = [x * 2 for x in lista]
fim_lista   = time.time()

tempo = (fim_lista - inicio_lista) / (fim_array - inicio_array)

Qual abordagem será que levou menos tempo?

In [31]:
print('Tempo necessário para a realização dos cálculos utilizando arrays: {:.4f} segundos'.format(fim_array - inicio_array))
print('Tempo necessário para a realização dos cálculos utilizando listas: {:.4f} segundos'.format(fim_lista - inicio_lista))
print('\nA abordagem de listas demorou {:.0f}x mais tempo! Esqueça listas e use arrays :)'.format(tempo - 1))

Tempo necessário para a realização dos cálculos utilizando arrays: 0.0447 segundos
Tempo necessário para a realização dos cálculos utilizando listas: 3.0513 segundos

A abordagem de listas demorou 67x mais tempo! Esqueça listas e use arrays :)


## Solução de sistema de equações lineares

Chega de exemplos vazios, vamos usar o NumPy para resolver um problema concreto e que nos é muito familiar: a solução de sistemas de equações lineares. Considere o sistema linear de equações dado por

A função `*np.linalg.solve*` é um método do NumPy que permite resolver sistemas de equações lineares do tipo Ax = B, onde A é uma matriz de coeficientes, x é o vetor de incógnitas que queremos encontrar e B é o vetor de constantes.

A sintaxe é a seguinte: **X = np.linalg.solve(A, B)**

A é a matriz de coeficientes do sistema de equações.

B é o vetor de constantes do sistema de equações.

X é o vetor de soluções, ou seja, as valores das incógnitas que satisfazem as equações.

In [32]:
# Definindo as equações do sistema
# x + 2y - z = 2
# 2x - y + z = 3
# x + y + z = 6

# Coeficientes das incógnitas
A = np.array([[1, 2, -1],
              [2, -1, 1],
              [1, 1, 1]])

# Constantes dos termos independentes
B = np.array([2, 3, 6])

# Resolvendo o sistema de equações lineares
X = np.linalg.solve(A, B)

# Imprimindo a solução
print("O valor das incógnitas é:")
print("x =", X[0])
print("y =", X[1])
print("z =", X[2])


O valor das incógnitas é:
x = 1.0
y = 2.0
z = 3.0
