# **Biblioteca NumPy**

## Introdução 
*Olá devers, beleza?*


Hoje faremos uma introdução a biblioteca NumPy, explorando recursos básicos e conceitos da biblioteca utilizada na geração dos dados da **primeira imagem de um buraco negro!**


Além disso, vamos abordar a aplicabilidade dessa biblioteca por meio de exemplos práticos e usos no cotidiano.
<br><br>
<div align="center">
    <img src="https://i.redd.it/791y1x3j2ou41.png" alt="titulo" width="300px" />
</div>


## **O que é o NumPy?**
É uma biblioteca (conjunto de módulos,funções e classes pré-definidos) em Python que permite a manipulação de dados homogêneos dentro de um elemento conhecido como *Array*. 

*Pontos positivos:* 
- Apesar de realizar tarefas que já existem dentro do Python (que seriam feitas em iterables built-in), o numpy fornece maior velocidade e eficiência de processos numéricos, diminuindo o uso de loops no código em comparação aos códigos tradicionais, além de realizar operações vetorizadas.

- Além disso possui integração com outras bibliotecas externas como o **Pandas**, **Seaborn** e **MatPlotLib**, facilitando a manipulação de dados.

*Pontos negativos:*
- Lida apenas com dados homogêneos, dificultando operações entre dados string, booleans e numéricos dentro de um vetor.

- Não possui uma integração tão básica com funções built-in, sendo as vezes restringida as suas próprias funções internas.


###### * Também traz um decréscimo no uso de memória RAM e processamento devido a ser uma biblioteca programada em C, uma linguagem de baixo nível.


In [3]:
# Começaremos importando a biblioteca, como na imagem acima
import numpy as np

### Array e dimensionamento:

Um dos benefícios dessa biblioteca consiste na facilidade com trabalhar e operar "listas" de dados (arrays), principalmente os numéricos. Para isso começaremos entendendo como funciona a função np.array()

In [4]:
array_lin_ex = np.array([1,6,7])
print(f' Exemplo de array com apenas uma linha:{array_lin_ex}')

print("-" * 60)

array_matrix_2x2 = np.array([[1,2],[6,7]])
print(f'''Exemplo de array bidimensional:
{array_matrix_2x2}''')

print("-" * 60)

array_matrix_3x4 = np.array([[6,0,100],[17,16,54],[20,49,48],[45,79,24]])
print(f'''Exemplo de array multidimensional:
{array_matrix_3x4}''')

 Exemplo de array com apenas uma linha:[1 6 7]
------------------------------------------------------------
Exemplo de array bidimensional:
[[1 2]
 [6 7]]
------------------------------------------------------------
Exemplo de array multidimensional:
[[  6   0 100]
 [ 17  16  54]
 [ 20  49  48]
 [ 45  79  24]]


### Atributos de array

In [47]:
arr = np.array([['a','e',0,True],['1',5,6,False]])

# Tamanho do array
tamanho_array = arr.shape

# Tipo do Array
tipo_array = arr.dtype

# Memória armazenada
ram_array = arr.data

# Número de dimensões do array 
ndimensoes_array = array_matrix_3x4.ndim

print(f'''{arr}
--------------------------------------------------      
|  Atributos:                                    |
| - Tamanho da matriz = {tamanho_array} ;                 |
| - Tipo de dado da matriz = {tipo_array} ;              |
| - Número de dimensões = {ndimensoes_array}                      |
--------------------------------------------------''')


[['a' 'e' '0' 'True']
 ['1' '5' '6' 'False']]
--------------------------------------------------      
|  Atributos:                                    |
| - Tamanho da matriz = (2, 4) ;                 |
| - Tipo de dado da matriz = <U11 ;              |
| - Número de dimensões = 2                      |
--------------------------------------------------
