# **Biblioteca NumPy**

## Introdução 
*Olá devers, beleza?*


Hoje faremos uma introdução a biblioteca NumPy, explorando recursos básicos e conceitos da biblioteca utilizada na geração dos dados da ***primeira imagem de um buraco negro!***


Além disso, vamos abordar a aplicabilidade dessa biblioteca por meio de exemplos práticos e usos no cotidiano.
<br><br>
<div align="center">
    <img src="https://i.redd.it/791y1x3j2ou41.png" alt="titulo" width="300px" />
</div>


In [14]:
# Começaremos importando a biblioteca, como na imagem acima
import numpy as np

### Array e dimensionamento:

Um dos benefícios dessa biblioteca consiste na facilidade com trabalhar e operar "listas" de dados (arrays), principalmente os numéricos. Para isso começaremos entendendo como funciona a função np.array(), o que é isso e as dimensões distintas de array.

In [17]:
array_lin_ex = np.array([1,6,7])
print(f' Exemplo de array com apenas uma linha:{array_lin_ex}')

print("-" * 60)

array_matrix_2x2 = np.array([[1,2],[6,7]])
print(f'''Exemplo de array bidimensional:
{array_matrix_2x2}''')

print("-" * 60)

array_matrix_3x4 = np.array([[6,0,100],[17,16,54],[20,49,48],[45,79,24]])
print(f'''Exemplo de array multidimensional:
{array_matrix_3x4}''')

 Exemplo de array com apenas uma linha:[1 6 7]
------------------------------------------------------------
Exemplo de array bidimensional:
[[1 2]
 [6 7]]
------------------------------------------------------------
Exemplo de array multidimensional:
[[  6   0 100]
 [ 17  16  54]
 [ 20  49  48]
 [ 45  79  24]]


Operações com arrays

arrays --> tipo de dado homogeneo, explicar o array
-se tentar heterogeneo converte todos para o mesmo tipo
- pode se realizar operações com arrays de tipo numérico
- array vs lista
-- listas permitem dados heterogeneos
-- array são mais rápidos, menor armazenamento e maior flexibilidade nos cálculos matemáticos
-- é possível fazer cálculos com o array como se fosse um número (altera a lista por inteiro)


In [5]:
np.zeros(5)
np.ones(4)
#aleatório
np.empty(3)
#sequencial
np.arange(10)
np.arange(0,10,5) #inicio, fim e step
# array sequencial espaçado linearmente
np.linspace(0,22, num=5)
#array aleatório bidimensional
np.random.random((2,4))
# array identidade
np.identity(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# Precisa ter o mesmo número de colunas
array_a = np.array([4,3,1])
array_b = np.array([6,4,1])
c = np.concatenate((a,b))
x = np.sort(c)

In [ ]:
# filtrando numeros divisiveis por 2
c_crescente[(x % 2 == 0)]
# filtrando numeros divisiveis por 2 e por 5
c_crescente[(x % 2 == 0)] & [(x%5 ==0)]
# substituir números que não são divisíveis por 3 pelo número 0
np.where(c_crescente % 3 ==0,c_crescente,0)


In [8]:
# teste de eficiência
import time
start_time = time.time()

array_100000 = np.random.randint(0,1001,size=100_000)

end_time = time.time()

print(f'resultado calculado em {(end_time-start_time)//60} minutos e {(end_time-start_time)%60} segundos.')

[873 526 854 ... 265  63 513]
resultado calculado em 0.0 minutos e 0.01600170135498047 segundos.


In [ ]:
# Operações com array
array_100000.shape
array_100000[0:100]
array_100000.min()
array_100000.max()
array_100000.sum()
array_100000.mean()
array_100000.var()
array_100000.std()


In [14]:
g = np.array([[1,7],[24,12],[80,33],[57,99],[6,60]]) #cada vírgula entre [],[] separa em linhas distintas e vírgula dentro do [,] separa em coluna 
# esse array tem 5 linhas e 2 colunas
print(g,g.shape)
g_flat = g.flatten()
print("-"*40)
print(g_flat)
print("-"*40)
g_reshape = g.reshape(2,5) #linha coluna
print(g_reshape)

[[ 1  7]
 [24 12]
 [80 33]
 [57 99]
 [ 6 60]] (5, 2)
----------------------------------------
[ 1  7 24 12 80 33 57 99  6 60]
----------------------------------------
[[ 1  7 24 12 80]
 [33 57 99  6 60]]


In [25]:
# conversão de array
g = np.array([1,3,5],dtype=np.float32)
g

array([1., 3., 5.], dtype=float32)